arrowParens: always
bracketSameLine: false
bracketSpacing: true
checkIgnorePragma: false
cursorOffset: -1
embeddedLanguageFormatting: auto
endOfLine: lf
experimentalOperatorPosition: end
experimentalTernaries: false
htmlWhitespaceSensitivity: css
insertPragma: false
jsxSingleQuote: false
objectWrap: preserve
printWidth: 80
proseWrap: preserve
quoteProps: as-needed
semi: true
singleAttributePerLine: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
